### ISSUE TITLE
En Chrome no se puede escribir bajo el ícono

### ISSUE THREAD

**Issue by alikathe** [eadpucv/pix#6]
En chrome, en mac, aparece el ícono bien al tipear y usar el autocomplete, pero no aparece lo escrito hacia abajo. Pareciera que se escribe en blanco hacia el lado, con caracteres del tamaño del ícono. Tengo una imagen para tratar de explicar.
![bug ejemplo 1](https://cloud.githubusercontent.com/assets/7327263/5805300/5978152e-9fec-11e4-8347-8c2dcb68cfdb.png)
![bug ejemplo 2](https://cloud.githubusercontent.com/assets/7327263/5805307/6a531e0c-9fec-11e4-87ee-93fea3acb86f.png)

**Comment by hugosolar** [comment]
esto ya está corregido
hago mención de esto en el issue #4
