### ISSUE TITLE
El botón "eliminar columna" no funciona bien

### ISSUE THREAD

**Issue by hspencer** [eadpucv/pix#9]
Noté que el botón eliminar no funciona siempre. Sólo funciona al eliminar una columna creada con el botón "crear columna" pero no para las columnas hechas con TAB. Es súper extraño este comportamiento (visto en firefox)

**Comment by hugosolar** [comment]
Corregido
se unificó el comportamiento
esto ocurría porque utilizaba 2 funciones, una para agregar la columna contextual y otra para agregarla al final, ahora modifiqué la función y es una sola por lo tanto tiene el mismo comportamiento
los cambios estan en la rama develop
